Repository bounswe/bounswe2024group9, pull requests merged in 2024-11, with the labels that each got.

#256 fix wikidata ban by adding agent
  django_project_491/django_app/views.py
Labels: ASAP, back end

#265 Lab6
  django_project_491/django_app/migrations/0009_user_interested_topics_user_known_languages.py
  django_project_491/django_app/models.py
  django_project_491/django_app/urls.py
  django_project_491/django_app/views.py
  django_project_491/requirements.txt
  docker-compose.yml
  koduyorum-web/package-lock.json
  koduyorum-web/package.json
  koduyorum-web/src/App.js
  koduyorum-web/src/Feed.css
  koduyorum-web/src/Feed.js
  koduyorum-web/src/Login.js
  koduyorum-web/src/PageComponents.js
  koduyorum-web/src/PostPreview.css
  koduyorum-web/src/PostPreview.js
  koduyorum-web/src/PostQuestion.css
  koduyorum-web/src/PostQuestion.js
  koduyorum-web/src/SearchResults.css
  koduyorum-web/src/SearchResults.js
  koduyorum-web/src/Signup.js
  koduyorum-web/src/SurveyPage.css
  koduyorum-web/src/SurveyPage.js
  koduyorum-web/src/components/code-execution.jsx
Labels: assigned to everyone, ASAP, design

#257 added computer science term and algorithmic paradigm
  django_project_491/django_app/views.py
Labels: back end

#280 Wikidata Searching Enhancement and Unit Tests
  django_project_491/django_app/test.py
  django_project_491/django_app/views/utilization_views.py
Labels: enhancement, back end

#293 Results Page Enhancement
  koduyorum-web/src/Feed.js
  koduyorum-web/src/SearchResults.css
  koduyorum-web/src/SearchResults.js
  koduyorum-web/src/SearchResults.test.js
Labels: ASAP, front end

#297 Optimize Backend for Performance Improvements
  django_project_491/django_app/urls.py
  django_project_491/django_app/views/question_views.py
  koduyorum-web/src/AuthWrapper.js
  koduyorum-web/src/Feed.js
  koduyorum-web/src/index.js
Labels: enhancement

#302 updated error handling for code execution
  django_project_491/django_app/models.py
  django_project_491/django_app/views/utilization_views.py
  koduyorum-web/src/components/code-execution.jsx
Labels: priority: high

#306 Integration Test - Wiki Search and Result
  django_project_491/django_app/test.py
Labels: ASAP, testing

#308 Web UI/ux
  django_project_491/django_app/views/question_views.py
  koduyorum-web/src/Feed.js
  koduyorum-web/src/PostPreview.css
  koduyorum-web/src/PostPreview.js
  koduyorum-web/src/SearchResults.css
  koduyorum-web/src/SearchResults.js
Labels: ASAP, front end

#294 Enhancements for Feed & Profile Page
  django_project_491/django_app/Utils/utils.py
  django_project_491/django_app/migrations/0003_user_name_user_surname.py
  django_project_491/django_app/migrations/0004_remove_user_bookmarks_user_bookmarks.py
  django_project_491/django_app/migrations/0005_comment_language.py
  django_project_491/django_app/models.py
  django_project_491/django_app/templates/password_reset_email.html
  django_project_491/django_app/urls.py
  django_project_491/django_app/views/comment_views.py
  django_project_491/django_app/views/question_views.py
  django_project_491/django_app/views/user_views.py
  django_project_491/django_app/views/utilization_views.py
  django_project_491/django_project_491/settings.py
  django_project_491/requirements.txt
  koduyorum-web/public/resources/default-pp.jpeg
  koduyorum-web/public/resources/login-signup-bg.png
  koduyorum-web/src/App.js
  koduyorum-web/src/Feed.css
  koduyorum-web/src/Feed.js
  koduyorum-web/src/ForgotPassword.js
  koduyorum-web/src/Login.js
  koduyorum-web/src/PageComponents.js
  koduyorum-web/src/Profile.css
  koduyorum-web/src/Profile.js
  koduyorum-web/src/ResetPassword.css
  koduyorum-web/src/ResetPassword.js
  koduyorum-web/src/Signup.js
  koduyorum-web/src/login_signup_style.css
Labels: ASAP, back end, front end, web

#309 Backend label additions
  django_project_491/django_app/migrations/0006_topic.py
  django_project_491/django_app/models.py
  django_project_491/django_app/urls.py
  django_project_491/django_app/views/question_views.py
  django_project_491/topics.json
Labels: back end

#315 Mobile annotation
  django_project_491/django_app/migrations/0006_annotation.py
  django_project_491/django_app/models.py
  django_project_491/django_app/urls.py
  django_project_491/django_app/views/annotation_views.py
  django_project_491/django_app/views/question_views.py
  django_project_491/django_app/views/user_views.py
  django_project_491/django_app/views/utilization_views.py
  koduyorum-web/src/Annotation.css
  koduyorum-web/src/CreateAnnotation.js
  koduyorum-web/src/SearchResults.js
  koduyorum/App.tsx
  koduyorum/__tests__/Login.test.tsx
  koduyorum/assets/pp.jpg
  koduyorum/package-lock.json
  koduyorum/package.json
  koduyorum/src/CreateQuestion.tsx
  koduyorum/src/InterestPage.tsx
  koduyorum/src/LabelDetailScreen.tsx
  koduyorum/src/PostDetail.tsx
  koduyorum/src/ProfilePage.tsx
  koduyorum/src/QuestionCard.tsx
  koduyorum/src/QuestionList.tsx
  koduyorum/src/Signup.tsx
  koduyorum/src/TopContributorsPage.tsx
  koduyorum/src/WikiResultDetail.tsx
Labels: ASAP, back end, mobile

#307 Add unittests for models and view functions
  .gitignore
  django_project_491/django_app/migrations/0007_merge_0006_annotation_0006_topic.py
  django_project_491/django_app/models.py
  django_project_491/django_app/test.py
  django_project_491/django_app/urls.py
  django_project_491/django_app/views/comment_views.py
  django_project_491/django_app/views/question_views.py
Labels: priority: high, testing
