Repository bounswe/bounswe2024group9, pull requests merged in 2024-10, with the labels that each got.

#213 Code Execution API connection
  README.md
  django_project_491/django_app/Utils/forms.py
  django_project_491/django_app/Utils/utils.py
  django_project_491/django_app/templates/run_code.html
  django_project_491/django_app/test.py
  django_project_491/django_app/tests.py
  django_project_491/django_app/urls.py
  django_project_491/django_app/views.py
  requirements.txt
Labels: priority: high, testing

#214 init: fetching data from wikipedia
  django_project_491/django_app/Utils/utils.py
  django_project_491/django_app/templates/wikipedia_data.html
  django_project_491/django_app/urls.py
  django_project_491/django_app/views.py
Labels: priority: high, discussion

#223 Wiki search and result
  django_project_491/django_app/test.py
  django_project_491/django_app/urls.py
  django_project_491/django_app/views.py
Labels: ASAP, back end

#227 Merging the changes at backend with the frontend
  .gitignore
  koduyorum-web/.gitignore
  koduyorum-web/README.md
  koduyorum-web/package-lock.json
  koduyorum-web/package.json
  koduyorum-web/public/favicon.ico
  koduyorum-web/public/index.html
  koduyorum-web/public/logo192.png
  koduyorum-web/public/logo512.png
  koduyorum-web/public/manifest.json
  koduyorum-web/public/robots.txt
  koduyorum-web/src/App.css
  koduyorum-web/src/App.js
  koduyorum-web/src/App.test.js
  koduyorum-web/src/Feed.js
  koduyorum-web/src/Forgot.js
  koduyorum-web/src/Login.js
  koduyorum-web/src/Signup.js
  koduyorum-web/src/hooks/AuthProvider.js
  koduyorum-web/src/index.css
  koduyorum-web/src/index.js
  koduyorum-web/src/login_signup_style.css
  koduyorum-web/src/logo.svg
  koduyorum-web/src/reportWebVitals.js
  koduyorum-web/src/setupTests.js
  package-lock.json
Labels: priority: low, front end

#236 redo deleted wiki search and result components
  django_project_491/django_app/Utils/utils.py
  django_project_491/django_app/test.py
  django_project_491/django_app/urls.py
  django_project_491/django_app/views.py
Labels: bug, minor adjustments, ASAP, back end

#244 Dockerize
  django_project_491/Dockerfile
  django_project_491/django_project_491/settings.py
  django_project_491/manage.py
  django_project_491/requirements.txt
  docker-compose.yml
  koduyorum-web/Dockerfile
Labels: ASAP
