Repository bounswe/bounswe2024group9, pull requests merged in 2024-12, with the labels that each got.

#312 Merge web front unified into main
  koduyorum-web/src/ResetPassword.css
Labels: ASAP, front end, web

#333 Add bookmarks to the frontend
  django_project_491/django_app/urls.py
  django_project_491/django_app/views/question_views.py
  koduyorum-web/src/PostPreview.js
  koduyorum-web/src/Profile.js
  koduyorum-web/src/components/code-execution.jsx
Labels: priority: high, discussion, back end, front end

#347 Mobile/annotation
  django_project_491/annotations_app/migrations/0001_initial.py
  django_project_491/annotations_app/models.py
  django_project_491/django_app/migrations/0002_question_type.py
  django_project_491/django_app/models.py
  django_project_491/django_app/urls.py
  django_project_491/django_app/views/annotation_views.py
  django_project_491/django_app/views/question_views.py
  django_project_491/django_app/views/user_views.py
  django_project_491/django_app/views/utilization_views.py
  koduyorum-web/src/Comment.js
  koduyorum-web/src/CreateAnnotation.js
  koduyorum-web/src/EditQuestion.js
  koduyorum-web/src/Feed.js
  koduyorum-web/src/PageComponents.js
  koduyorum-web/src/PostPreview.css
  koduyorum-web/src/PostPreview.js
  koduyorum-web/src/PostQuestion.css
  koduyorum-web/src/PostQuestion.js
  koduyorum-web/src/QuestionDetail.js
  koduyorum-web/src/SearchResults.js
  koduyorum-web/src/components/code-execution.jsx
  koduyorum/App.tsx
  koduyorum/android/app/build.gradle
  koduyorum/src/BookmarksPage.tsx
  koduyorum/src/CreateQuestion.tsx
  koduyorum/src/CustomSyntaxHighlighter.tsx
  koduyorum/src/DiscussionDetail.tsx
  koduyorum/src/PostDetail.tsx
  koduyorum/src/ProfilePage.tsx
  koduyorum/src/QuestionCard.tsx
  koduyorum/src/QuestionDetail.tsx
  koduyorum/src/QuestionList.tsx
  koduyorum/src/WikiResultDetail.tsx
Labels: ASAP

#348 Add annotations to the question page
  django_project_491/django_app/views/question_views.py
  django_project_491/requirements.txt
  koduyorum-web/src/Comment.js
  koduyorum-web/src/CreateAnnotation.js
  koduyorum-web/src/QuestionDetail.js
  koduyorum-web/src/SearchResults.js
  koduyorum-web/src/components/code-execution.jsx
Labels: ASAP, back end, front end

#356 Mobile/user search final fixes
  django_project_491/django_app/views/user_views.py
  koduyorum/src/BookmarksPage.tsx
  koduyorum/src/DiscussionDetail.tsx
  koduyorum/src/QuestionCard.tsx
Labels: ASAP

#359 Unittests integritytests
  django_project_491/django_app/test.py
Labels: ASAP, testing
